items/urls.py
# PEP8
# Imports
from django.urls import path
from django.contrib.auth.decorators import login_required
from items import views


urlpatterns = [
    path("<int:category_pk>/", views.ShopView.as_view(), name="shop"),
    path(
        "item-detail/<int:item_pk>/",
        views.ItemDetailView.as_view(),
        name="item-detail",
    ),
    path(
        "submit-comment/<int:item_pk>/",
        login_required(views.ItemDetailView.submit_comment),
        name="submit-comment",
    ),
    path(
        "item-like/<int:item_pk>/",
        login_required(views.ItemLikeView.as_view()),
        name="item-like",
    ),
    path(
        "item-dislike/<int:item_pk>/",
        login_required(views.ItemDislikeView.as_view()),
        name="item-dislike",
    ),
]

ohmazing_components/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('', include('landing.urls')),
    path("owner/", include("owner.urls")),
    path("profilemanager/", include("profilemanager.urls")),
    path("items/", include("items.urls")),
    path("wishlist/", include("wishlist.urls")),
    path("vault/", include("vault.urls")),
    path("checkout/", include("checkout.urls")),
    path("history/", include("history.urls")),
    path("favicon.ico", RedirectView.as_view(
        url="/static/images/favicon.png")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner/urls.py
# PEP8
# Imports
from django.urls import path
from django.contrib.auth.decorators import login_required
from owner import views

urlpatterns = [
    path("", login_required(views.OwnerMainView.as_view()), name="owner"),
    path(
        "category-delete-request/<int:category_pk>",
        login_required(views.DeleteCategoryView.category_delete_request),
        name="category-delete-request",
    ),
    path(
        "delete-category/<int:category_pk>/",
        login_required(views.DeleteCategoryView.as_view()),
        name="delete-category",
    ),
    path(
        "add-category/",
        login_required(views.AddCategoryView.as_view()),
        name="add-category",
    ),
    path(
        "edit-category/<int:category_pk>/",
        login_required(views.EditCategoryView.as_view()),
        name="edit-category",
    ),
    path(
        "items/", login_required(views.OwnerItemsView.as_view()), name="items"
    ),
    path(
        "item-delete-request/<int:item_pk>",
        login_required(views.DeleteItemView.item_delete_request),
        name="item-delete-request",
    ),
    path(
        "add-item/",
        login_required(views.AddItemView.as_view()),
        name="add-item",
    ),
    path(
        "edit-item/<int:item_pk>/",
        login_required(views.EditItemView.as_view()),
        name="edit-item",
    ),
    path(
        "delete-item/<int:item_pk>/",
        login_required(views.DeleteItemView.as_view()),
        name="delete-item",
    ),
    path(
        "invoices/",
        login_required(views.OwnerInvoicesView.as_view()),
        name="invoices",
    ),
    path(
        "view-invoice/<int:invoice_pk>/",
        login_required(views.ViewInvoiceView.as_view()),
        name="view-invoice",
    ),
    path(
        "download-invoice/<int:invoice_pk>/",
        login_required(views.DownloadInvoiceView.as_view()),
        name="download-invoice",
    ),
    path(
        "postage-settings/",
        login_required(views.PostageSettingsView.as_view()),
        name="postage-settings",
    ),
    path(
        "comments/",
        login_required(views.CommentsOwnerView.as_view()),
        name="comments-owner",
    ),
    path(
        "comment-delete-request/<int:comment_pk>",
        login_required(views.DeleteCommentView.comment_delete_request),
        name="comment-delete-request",
    ),
    path(
        "delete-comment/<int:comment_pk>/",
        login_required(views.DeleteCommentView.as_view()),
        name="delete-comment",
    ),
    path(
        "approve-comment/<int:comment_pk>/",
        login_required(views.ApproveCommentView.as_view()),
        name="approve-comment",
    ),
    path(
        "vouchers/",
        login_required(views.VouchersOwnerView.as_view()),
        name="vouchers-owner",
    ),
    path(
        "add-voucher/",
        login_required(views.AddVoucherView.as_view()),
        name="add-voucher",
    ),
    path(
        "voucher-delete-request/<int:voucher_pk>",
        login_required(views.DeleteVoucherView.voucher_delete_request),
        name="voucher-delete-request",
    ),
    path(
        "delete-voucher/<int:voucher_pk>/",
        login_required(views.DeleteVoucherView.as_view()),
        name="delete-voucher",
    ),
    path(
        "edit-voucher/<int:voucher_pk>/",
        login_required(views.EditVoucherView.as_view()),
        name="edit-voucher",
    ),
    path(
        "emails/",
        login_required(views.EmailsOwnerView.as_view()),
        name="emails-owner",
    ),
    path(
        "new-email/",
        login_required(views.NewEmailView.as_view()),
        name="new-email",
    ),
    path(
        "email-delete-request/<int:email_pk>",
        login_required(views.DeleteEmailView.email_delete_request),
        name="email-delete-request",
    ),
    path(
        "delete-email/<int:email_pk>/",
        login_required(views.DeleteEmailView.as_view()),
        name="delete-email",
    ),
    path(
        "edit-email/<int:email_pk>/",
        login_required(views.EditEmailView.as_view()),
        name="edit-email",
    ),
]

items/models.py
# PEP8
# Imports
from django_resized import ResizedImageField
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


class Category(models.Model):
    """
    Model for shop categories
    """

    category_name = models.CharField(max_length=254)
    category_image = ResizedImageField(
        size=[400, 400],
        crop=["middle", "center"],
        quality=75,
        upload_to="category_images/",
        force_format="WEBP",
        blank=True,
    )

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name


class Item(models.Model):
    """
    Model for shop items
    """

    # Set choices  for sizes, values and VAT rates
    HAS_SIZES = (
        (0, "No - Item has no sizes"),
        (1, "Yes - Item has different sizes"),
    )
    HAS_VALUES = (
        (0, "No - Item has no values"),
        (1, "Yes - Item has different values"),
    )
    VAT_RATES = (
        (0, "23 % VAT"),
        (1, "13.5 % VAT"),
        (2, "9 % VAT"),
        (3, "0 % VAT"),
    )

    item_sku = models.CharField(max_length=254, null=True, blank=False)
    item_name = models.CharField(max_length=254, unique=True)
    item_description = models.TextField(blank=False)
    price_per_unit = models.DecimalField(max_digits=6, decimal_places=2)
    item_vat_rate = models.IntegerField(choices=VAT_RATES, default=0)
    item_category = models.ManyToManyField(
        Category,
        blank=False,
        help_text="Select more categories by CTRL + click",
    )
    different_sizes = models.IntegerField(
        choices=HAS_SIZES,
        default=0,
        help_text="Select yes if item comes in different package sizes",
    )
    sizes = ArrayField(
        models.CharField(max_length=100),
        blank=True,
        null=True,
        help_text='Separate sizes by comma ","',
    )
    different_values = models.IntegerField(
        choices=HAS_VALUES,
        default=0,
        help_text="Select yes if item comes in different values",
    )
    values = ArrayField(
        models.CharField(max_length=100),
        blank=True,
        null=True,
        help_text='Separate values by comma ","',
    )
    image_1 = ResizedImageField(
        size=[400, 400],
        crop=["middle", "center"],
        quality=75,
        upload_to="item_images/",
        force_format="WEBP",
        blank=True,
    )
    image_2 = ResizedImageField(
        size=[400, 400],
        crop=["middle", "center"],
        quality=75,
        upload_to="item_images/",
        force_format="WEBP",
        blank=True,
    )
    image_3 = ResizedImageField(
        size=[400, 400],
        crop=["middle", "center"],
        quality=75,
        upload_to="item_images/",
        force_format="WEBP",
        blank=True,
    )
    item_stock = models.IntegerField(default=0)
    item_likes = models.ManyToManyField(
        User, related_name="item_likes", blank=True
    )
    item_dislikes = models.ManyToManyField(
        User, related_name="item_dislikes", blank=True
    )
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.item_name

    def rating_counter(self):
        """
        Method returns item rating based on likes and dislikes
        """
        return self.item_likes.count() - self.item_dislikes.count()


class ItemComments(models.Model):
    """
    Model for shop item comments
    """

    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name="item_comments",
    )
    comment_author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="items"
    )
    comment_body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]
        verbose_name = "Item Comment"

    def __str__(self):
        return f"Comment {self.comment_body} by {self.comment_author}"

items/forms.py
# PEP8
# Imports
from items.models import ItemComments
from django import forms


class ItemCommentForm(forms.ModelForm):
    """Form for comments"""

    class Meta:
        model = ItemComments
        fields = ("comment_body",)

    def __init__(self, *args, **kwargs):
        """
        Method init to se up form properties
        """
        super().__init__(*args, **kwargs)
        self.fields["comment_body"].widget.attrs.update(
            {
                "rows": 3,
                "placeholder": "Type your comment here ...",
                "aria-label": "News Comment",
                "class": "shadow-none",
            }
        )

owner/forms.py
# PEP8
# Imports
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor.widgets import CKEditorWidget
from owner.widgets import (
    CustomImageInputCategory,
    CustomImageInputItem1,
    CustomImageInputItem2,
    CustomImageInputItem3,
)
from items.models import Category, Item
from owner.models import PostageSettings, Voucher, Newsletter, NewsletterEmail


class CategoryForm(forms.ModelForm):
    """
    Category form
    """

    class Meta:
        model = Category
        fields = (
            "category_name",
            "category_image",
        )

    def __init__(self, *args, **kwargs):
        """
        Initial medthod
        """
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields["category_name"].widget.attrs.update(
            {
                "placeholder": "Enter category name (required)",
                "class": "shadow-none",
            }
        )

    category_image = forms.ImageField(
        label="Category Image", required=False, widget=CustomImageInputCategory
    )


class ItemForm(forms.ModelForm):
    """
    Item form
    """

    class Meta:
        model = Item
        exclude = ["item_dislikes", "item_likes", "date_added"]

    def __init__(self, *args, **kwargs):
        """
        Initial method
        """
        super(ItemForm, self).__init__(*args, **kwargs)
        fields_to_add_class = self.fields.keys()
        for field in fields_to_add_class:
            self.fields[field].widget.attrs.update(
                {
                    "class": "shadow-none",
                }
            )
        self.fields["item_name"].widget.attrs.update(
            {"placeholder": "Enter item name (required)"}
        )
        self.fields["item_sku"].widget.attrs.update(
            {"placeholder": "Enter item SKU (required)"}
        )
        self.fields["price_per_unit"].widget.attrs.update(
            {
                "placeholder": "Enter price per unit (required)",
                "step": "0.05",
                "min": "0",
            }
        )
        self.fields["price_per_unit"].validators.append(MinValueValidator(0))
        self.fields["item_description"].widget.attrs.update(
            {
                "placeholder": "Enter item description (required)",
                "rows": 3,
            }
        )
        self.fields["item_stock"].widget.attrs.update(
            {
                "placeholder": "Enter current stock amount",
                "step": "1",
                "min": "0",
            }
        )

    image_1 = forms.ImageField(
        label="Image 1", required=False, widget=CustomImageInputItem1
    )
    image_2 = forms.ImageField(
        label="Image 2", required=False, widget=CustomImageInputItem2
    )
    image_3 = forms.ImageField(
        label="Image 3", required=False, widget=CustomImageInputItem3
    )


class PostageSettingsForm(forms.ModelForm):
    """
    Postage form
    """

    class Meta:
        model = PostageSettings
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        """
        Initial method
        """
        super(PostageSettingsForm, self).__init__(*args, **kwargs)
        fields_to_add_class = self.fields.keys()
        for field in fields_to_add_class:
            self.fields[field].widget.attrs.update(
                {
                    "class": "shadow-none",
                }
            )
        self.fields["free_postage"].widget.attrs.update(
            {
                "placeholder": "Free postage threshold € (required)",
                "step": "0.05",
                "min": "1",
            }
        )
        self.fields["standard_delivery"].widget.attrs.update(
            {
                "placeholder": "Postage cost % (required)",
                "step": "0.05",
                "min": "1",
            }
        )
        self.fields["express_delivery"].widget.attrs.update(
            {
                "placeholder": "Postage cost % (required)",
                "step": "0.05",
                "min": "1",
            }
        )
        self.fields["minimum_order"].widget.attrs.update(
            {
                "placeholder": "Minimum order € (required)",
                "step": "1",
                "min": "1",
            }
        )


class VoucherForm(forms.ModelForm):
    """
    Voucher form
    """

    class Meta:
        model = Voucher
        fields = "__all__"
        widgets = {
            "start_date": forms.DateInput(attrs={"type": "date"}),
            "end_date": forms.DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        """
        Initial method
        """
        super(VoucherForm, self).__init__(*args, **kwargs)
        fields_to_add_class = self.fields.keys()
        for field in fields_to_add_class:
            self.fields[field].widget.attrs.update(
                {
                    "class": "shadow-none",
                }
            )
        self.fields["discount"].widget.attrs.update(
            {
                "placeholder": "Enter % of discount",
                "step": "1",
                "min": "1",
                "max": "100",
            }
        )
        self.fields["voucher_code"].widget.attrs.update(
            {
                "placeholder": "Enter CODE of discount",
            }
        )

    discount = forms.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)]
    )


class NewsletterForm(forms.ModelForm):
    """
    Newsletter form
    """

    class Meta:
        model = Newsletter
        fields = "__all__"
        widgets = {
            "newsletter_email": forms.DateInput(
                attrs={"type": "email",
                       "placeholder": "your@email.ie",
                       "aria-label": "Newsletter Sign-Up"}
            ),
        }

    def __init__(self, *args, **kwargs):
        """
        Initial method
        """
        super(NewsletterForm, self).__init__(*args, **kwargs)
        fields_to_add_class = self.fields.keys()
        for field in fields_to_add_class:
            self.fields[field].widget.attrs.update(
                {
                    "class": "shadow-none",
                }
            )


class NewsletterEmailForm(forms.ModelForm):
    """
    Newsletter Emails form
    """

    class Meta:
        model = NewsletterEmail
        fields = ("subject", "body")

        body = forms.CharField(widget=CKEditorWidget())

    def __init__(self, *args, **kwargs):
        """
        Initial method
        """
        super(NewsletterEmailForm, self).__init__(*args, **kwargs)
        fields_to_add_class = self.fields.keys()
        for field in fields_to_add_class:
            self.fields[field].widget.attrs.update(
                {
                    "class": "shadow-none",
                }
            )

owner/templates/owner/categories.html
{% extends "owner/owner.html" %}
{% load static %}

{% block owner_admin %}
    <div class="col-12 d-flex flex-column">
        <h2 class="my-2 text-center">
            Categories
        </h2>
        <div class="d-flex justify-content-center p-3 w-100">
            <a href="{% url 'add-category' %}" aria-label="Add New Category" class="custom-button button-shadow">Add New Category</a>
        </div>
        <!-- If categories don't exist display message, row wrap = 3 -->
        {% if all_categories|length == 0 %}
            <p class="text-center">
                No categories to display.
            </p>
        <!-- Categories exist -->
        {% else %}
            <div>
            <!-- For each category -->
            {% for category in all_categories%}
                {% if forloop.first or forloop.counter == 4 or forloop.counter|add:"-1"|divisibleby:3 %}
                <div class="row">
                {% endif %}
                <div class="col-12 col-xl-4 text-center">
                    <div class="folder">
                        <h3 class="category-heading">
                            {{ category.category_name }}
                        </h3>
                        <!-- Display image if exists otherwise default -->
                        {% if category.category_image == '' or category.category_image == 'False' %}
                            <img src="{% static 'images/no_image.png' %}" alt="{{ category.category_name }} preview" class="category-preview">
                        {% else %}
                            <img src="{{ category.category_image.url }}" alt="{{ category.category_name }} preview" class="category-preview">
                        {% endif %}
                        <div class="row">
                            <!-- Category actions -->
                            <div class="col-12 d-flex justify-content-around my-2">
                                <a href="{% url 'edit-category' category_pk=category.pk %}" aria-label="Edit Category" class="custom-button button-shadow">Edit</a>
                                <a href="{% url 'category-delete-request' category_pk=category.pk %}" aria-label="Delete Category" class="custom-button button-shadow">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 or forloop.last %}
                </div>
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

owner/templates/owner/comment_delete_confirm.html
{% extends "base.html" %}
{% load static %}

{% block nav_name %}Confirm{% endblock %}

{% block extra_css %} 
        <link rel="stylesheet" href="{% static 'css/owner.css' %}">
{% endblock %}

{% block content %}
<div class="container wrapper d-flex justify-content-center align-items-center">
    <div class="form-background add-shadow">
        <!-- Display details of requested comment -->
        <div class="w-100 d-flex justify-content-end">
            <a href="{% url 'comments-owner' %}" aria-label="Close" class="close-form">
                <i class="bi bi-x"></i>
            </a>
        </div>
        <h1 class="text-center">
            Are you sure ?
        </h1>
        <p class="text-center">
            You are about to delete comment made by 
            <strong>
                {{ comment_to_delete.comment_author }}
            </strong>
            on 
            <strong>
                {{ comment_to_delete.created_on|date:"d.m.Y" }}
            </strong>
            .
        </p>
        <!-- Comment deletition options -->
        <div class="w-100 d-flex justify-content-around p-3">
            <a href="{% url 'comments-owner' %}" aria-label="No, take me back" class="custom-button button-shadow">
                No, take me back
            </a>
            <a href="{% url 'delete-comment' comment_pk=comment_to_delete.pk%}" aria-label="Yes, delete" class="custom-button button-shadow" id="deleteButton">
                Yes, delete
            </a>
        </div>
    </div>
</div>
{%endblock%}

{% block extra_js %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            // display loader if delete button clicked
            $('#deleteButton').click(function(){
                $('#loader-container').css("display", "flex");
            });
        });
    </script>
{% endblock %}

owner/templates/owner/edit_category.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block nav_name %}Edit Category{% endblock %}

{% block extra_css %}
<!-- Local styling to ensure this doesn't interfere with global styling of same class names -->
<style>
    .asteriskField {
        display: none;
    }
</style>
<link rel="stylesheet" href="{% static 'css/owner.css' %}">
{% endblock %}

{% block content %}
<div class="container wrapper d-flex justify-content-center align-items-center">
    <div class="form-background add-shadow">
        <div class="w-100 d-flex justify-content-end">
            <a href="{% url 'owner' %}" aria-label="Close" class="close-form">
                <i class="bi bi-x"></i>
            </a>
        </div>
        <!-- Display details of edited category -->
        <h1 class="text-center">
            Editing category {{ category_name }}
        </h1>
        <form method="post" enctype="multipart/form-data" id="form">
            {% csrf_token %}
            {{ edit_category_form.category_name|as_crispy_field }}
            <div class="w-100">
                {{ edit_category_form.category_image|as_crispy_field }}
            </div>
            <!-- Edit form submit -->
            <div class="container d-flex justify-content-around">
                <button type="submit" value="Submit" class="custom-button button-shadow mt-4" id="editSubmit">Submit changes</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            //  if no file selected - display message
            $('#filename').text(`No file selected.`);
            // if file input field changes
            $('#id_category_image').change(function() {
                // set string and file preview
                let file = $('#id_category_image')[0].files[0];
                $('#filename').text(`Image will be set to : ${file.name}`);
                // create file reader
                let reader = new FileReader();
                reader.onload = function(e) {
                    $("#image-preview").attr("src", e.target.result);
                };
                // execute file reader
                reader.readAsDataURL(file);
            });
            $('#form').submit(function(){
                // if form submitted, display loader
                $('#loader-container').css("display", "flex");
            });
        });
    </script>
{% endblock %}

owner/templates/owner/edit_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block nav_name %}Edit Item{% endblock %}

{% block extra_css %}
<!-- Local styling to ensure this doesn't interfere with global styling of same class names -->
<style>
    .asteriskField {
        display: none;
    }
</style>
<link rel="stylesheet" href="{% static 'css/owner.css' %}">
{% endblock %}

{% block content %}
<div class="container wrapper d-flex justify-content-center align-items-center">
    <div class="form-background add-shadow">
        <div class="w-100 d-flex justify-content-end">
            <a href="{% url 'items' %}" aria-label="Close" class="close-form">
                <i class="bi bi-x"></i>
            </a>
        </div>
        <!-- Display details of edited item -->
        <h1 class="text-center">
            Editing item {{ item_name }}
        </h1>
        <form method="post" enctype="multipart/form-data" id="form">
            {% csrf_token %}
            {{ edit_item_form|crispy }}
            <!-- Submit button -->
            <div class="container d-flex justify-content-around">
                <button type="submit" value="Submit" class="custom-button button-shadow mt-4" id="editSubmit">Submit changes</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            // prefill the text fields
            $('#filename-1, #filename-2, #filename-3').text(`No file selected.`);
            $('#id_image_1').change(function() {
                let file = $('#id_image_1')[0].files[0];
                $('#filename-1').text(`Image 1 will be set to : ${file.name}`);
            });
            // file inputs text change
            $('#id_image_2').change(function() {
                let file = $('#id_image_2')[0].files[0];
                $('#filename-2').text(`Image 2 will be set to : ${file.name}`);
            });
            $('#id_image_3').change(function() {
                let file = $('#id_image_3')[0].files[0];
                $('#filename-3').text(`Image 3 will be set to : ${file.name}`);
            });
            if ($('#id_different_values').val() == 0){
                $('#id_values,label[for="id_values"],#hint_id_values').hide();
            };
            if ($('#id_different_sizes').val() == 0){
                $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').hide();
            };
            // toggle values input if item has values
            $('#id_different_values').change(function(){
                if ($('#id_different_values').val() == 1){
                    $('#id_values,label[for="id_values"],#hint_id_values').show();
                } else {
                    $('#id_values,label[for="id_values"],#hint_id_values').hide();
                };
            });
            // togle sizes input field if item has different sizes
            $('#id_different_sizes').change(function(){
                if ($('#id_different_sizes').val() == 1){
                    $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').show();
                } else {
                    $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').hide();
                };
            });
            // if form submitted, display loader
            $('#form').submit(function(){
                $('#loader-container').css("display", "flex");
            });
        });
    </script>
{% endblock %}

owner/templates/owner/new_item.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block nav_name %}New Item{% endblock %}

{% block extra_css %}
<!-- Local styling to ensure this doesn't interfere with global styling of same class names -->
<style>
    .asteriskField {
        display: none;
    }
</style>
<link rel="stylesheet" href="{% static 'css/owner.css' %}">
{% endblock %}

{% block content %}
<div class="container wrapper d-flex justify-content-center align-items-center">
    <div class="form-background add-shadow">
        <div class="w-100 d-flex justify-content-end">
            <a href="{% url 'items' %}" aria-label="Close" class="close-form">
                <i class="bi bi-x"></i>
            </a>
        </div>
        <h1 class="text-center">
            New Item
        </h1>
        <form method="post" enctype="multipart/form-data" id="form">
            {% csrf_token %}
            {{ new_item_form|crispy }}
            <!-- New item submit button -->
            <div class="container d-flex justify-content-around">
                <button type="submit" value="Submit" class="custom-button button-shadow mt-4">Add Item</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            // Prefixes for filenames fields
            $('#filename-1, #filename-2, #filename-3').text(`No file selected.`);
            // If file changed display name in filename field
            $('#new-image-1').change(function() {
                let file = $('#new-image-1')[0].files[0];
                $('#filename-1').text(`Image 1 will be set to : ${file.name}`);
            });
            $('#new-image-2').change(function() {
                let file = $('#new-image-2')[0].files[0];
                $('#filename-2').text(`Image 2 will be set to : ${file.name}`);
            });
            $('#new-image-3').change(function() {
                let file = $('#new-image-3')[0].files[0];
                $('#filename-3').text(`Image 3 will be set to : ${file.name}`);
            });
            // Prehide sizes and values fields
            $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').hide();
            $('#id_values,label[for="id_values"],#hint_id_values').hide();
            // If has values changes, display or hide values field accordingly
            $('#id_different_values').change(function(){
                if ($('#id_different_values').val() == 1){
                    $('#id_values,label[for="id_values"],#hint_id_values').show();
                } else {
                    $('#id_values,label[for="id_values"],#hint_id_values').hide();
                };
            });
            // If has sizes changes, display or hide sizes field accordingly
            $('#id_different_sizes').change(function(){
                if ($('#id_different_sizes').val() == 1){
                    $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').show();
                } else {
                    $('#id_sizes,label[for="id_sizes"],#hint_id_sizes').hide();
                };
            });
            // if form submitted, display loader
            $('#form').submit(function(){
                $('#loader-container').css("display", "flex");
            });
        });
    </script>
{% endblock %}